import vue from 'vue'
import vuex from 'vuex'

import auth from './auth'
import profile from './profile'

vue.use(vuex)

let store = new vuex.Store({
  state: {
    interfaceWeek: 'week0',
    activeColumn: '',
    activeColumn2: '',
    subjects: [
      {
        day_week: 1,
        subject: "Функциональное программирование",
        number_column: 1
      },
      {
        day_week: 1,
        subject: "Введение в Data Mining",
        number_column: 2
      },
      {
        day_week: 1,
        subject: "Введение в Data Mining",
        number_column: 3
      },
      {
        day_week: 2,
        subject: "Математическое моделирование",
        number_column: 4
      },
      {
        day_week: 2,
        subject: "Эконометрика",
        number_column: 5
      },
      {
        day_week: 2,
        subject: "Информационная безопасность",
        number_column: 6
      },
      {
        day_week: 2,
        subject: "Технологии разработки ПО",
        number_column: 7
      },
      {
        day_week: 3,
        subject: "Информационная безопасность",
        number_column: 8
      },
      {
        day_week: 3,
        subject: "Математическое моделирование",
        number_column: 9
      },
      {
        day_week: 3,
        subject: "Разработка веб-сервисов",
        number_column: 10
      },
      {
        day_week: 3,
        subject: "Разработка веб-сервисов",
        number_column: 11
      },
      {
        day_week: 4,
        subject: "Эконометрика",
        number_column: 12
      },
      {
        day_week: 4,
        subject: "Компьютерные издательские системы",
        number_column: 13
      },
      {
        day_week: 4,
        subject: "Компьютерные издательские системы",
        number_column: 14
      },
    ],
    students: [
      {
        number: 1,
        name: 'Архипов В. И.'
      },
      {
        number: 2,
        name: 'Демьянов Леонид Олегович'
      },
      {
        number: 3,
        name: 'Загузин Дмитрий Александрович'
      },
      {
        number: 4,
        name: 'Закаулова Дарья Дмитриевна'
      },
      {
        number: 5,
        name: 'Зданович Дмитрий Алексеевич'
      },
      {
        number: 6,
        name: 'Карноухов Семен Александрович'
      },
      {
        number: 7,
        name: 'Карпов Егор Вадимович'
      },
      {
        number: 8,
        name: 'Катышев Артем Владимирович'
      },
      {
        number: 9,
        name: 'Козлов Алексей Александрович'
      },
      {
        number: 10,
        name: 'Мирошниченко Александр Денисович'
      },
      {
        number: 11,
        name: 'Новикова Алина Александровна'
      },
      {
        number: 12,
        name: 'Разуваев Михаил Сергеевич'
      },
      {
        number: 13,
        name: 'Стронский Андрей Игоревич'
      },
      {
        number: 14,
        name: 'Суздалев Руслан Анатольевич'
      },
      {
        number: 15,
        name: 'Томшин Артур Андреевич'
      },
      {
        number: 16,
        name: 'Халатян Мери Левоновна'
      },
      {
        number: 17,
        name: 'Ходжиев Александр Ходжимахмадович'
      },
      {
        number: 18,
        name: 'Циберман Николай Юрьевич'
      },
      {
        number: 19,
        name: 'Черепанов Игорь Андреевич'
      },
      {
        number: 20,
        name: 'Шубин Дмитрий Александрович'
      },
      {
        number: 21,
        name: 'Якимчук Артур Игоревич'
      },
    ],
    weeks: {
      week0: '1',
      week1: '8',
    },
    visits: {
      week0: {
        column01: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column02: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column03: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column04: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column05: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column06: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column07: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column08: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column09: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column10: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column11: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column12: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column13: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column14: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        } 
      },
      week1: {
        column01: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column02: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column03: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column04: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column05: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column06: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column07: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column08: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column09: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column10: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column11: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column12: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column13: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        },
        column14: {
          student01: 'n',
          student02: 'n',
          student03: 'n',
          student04: 'n',
          student05: 'n',
          student06: 'n',
          student07: 'n',
          student08: 'n',
          student09: 'n',
          student10: 'n',
          student11: 'n',
          student12: 'n',
          student13: 'n',
          student14: 'n',
          student15: 'n',
          student16: 'n',
          student17: 'n',
          student18: 'n',
          student19: 'n',
          student20: 'n',
          student21: 'n',
        } 
      },
    },
    visitTemaplate: {
      student01: 'n',
      student02: 'n',
      student03: 'y',
      student04: 'y',
      student05: 'n',
      student06: 'y',
      student07: 'y',
      student08: 'n',
      student09: 'y',
      student10: 'y',
      student11: 'n',
      student12: 'n',
      student13: 'y',
      student14: 'y',
      student15: 'n',
      student16: 'y',
      student17: 'n',
      student18: 'y',
      student19: 'y',
      student20: 'y',
      student21: 'y',
    }
  },
  mutations: {
    ChangeCellValue(state, cellData) {
      state.visits[state.interfaceWeek][cellData.column][cellData.student] = cellData.visit
    },
    ChangeActiveColumn(state, columnN) {
      state.activeColumn = columnN
    },
    toActiveVisitTemplate(state) {
      let columnN = 'column'
      if (String(state.activeColumn).length == 1) {
        columnN += 0
      }
      columnN += state.activeColumn 
      state.visits[state.interfaceWeek][columnN] = state.visitTemaplate
    }
  },
  actions: {
  },
  getters: {
    SUBJECTS(state) {
      return state.subjects
    },
    STUDENTS(state){
      return state.students
    },
    VISITS(state) {
      return state.visits
    },
    ACTIVECOLUMN(state) {
      return state.activeColumn
    }
  },
  modules: {
    auth,
    profile,
  }
})


export default store;
